### ISSUE TITLE
Compatibility with PHP 5.3

### ISSUE THREAD

**Issue by jairlopez** [fullfatthings/samesiteexceptions#7]
Hello Full Fat Things team,

I think it would be nice to make this library available for older versions of PHP as well.

I'm aware of how to do it but I wonder if you would find it useful for your library as well

Are you merging pull requests for this library?

**Comment by stewsnooze** [comment]
Hi,

We’d be happy to review and merge pull requests to add PHP5.3 support!

**Comment by jairlopez** [comment]
Great! Thanks for your reply @stewsnooze.

I'll work on it. One moment please.

**Comment by jeremyfrench** [comment]
@jairlopez raised #8
